files:
  - source: /Resources/Private/Language/
    ignore:
      - /Resources/Private/Language/de.*
      - /Resources/Private/Language/nl.*
    translation: /%original_path%/%two_letters_code%.%original_file_name%
